In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
path = "/content/drive/MyDrive/Dataset/preprocessed.csv"
path2 = "/content/drive/MyDrive/Dataset/stop_words.txt"

In [4]:
preprocessedDF = pd.read_csv(path, low_memory=False)

In [5]:
preprocessedDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37210 entries, 0 to 37209
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  37210 non-null  bool   
 1   belongs_to_collection  3918 non-null   object 
 2   budget                 37210 non-null  int64  
 3   genres                 37210 non-null  object 
 4   homepage               6307 non-null   object 
 5   id                     37210 non-null  int64  
 6   imdb_id                37210 non-null  int64  
 7   original_language      37205 non-null  object 
 8   original_title         37210 non-null  object 
 9   overview               36573 non-null  object 
 10  popularity             37210 non-null  float64
 11  poster_path            37210 non-null  object 
 12  production_companies   37210 non-null  object 
 13  production_countries   37210 non-null  object 
 14  release_date           37189 non-null  object 
 15  re

In [6]:
preprocessedDF.describe()

budget             id  ...           red       red_sd 
count  3.721000e+04   37210.000000  ...  37210.000000  37210.000000
mean   4.711716e+06   92095.604327  ...    127.214442     75.265465
std    1.820269e+07   97166.149197  ...     51.192335     15.793882
min    0.000000e+00       2.000000  ...      1.337270      1.244778
25%    0.000000e+00   22969.250000  ...     87.503894     65.441396
50%    0.000000e+00   51789.000000  ...    127.259378     75.881237
75%    0.000000e+00  125163.250000  ...    167.770281     86.003713
max    3.800000e+08  469172.000000  ...    253.605869    125.837170

[8 rows x 22 columns]

In [7]:
all_data = preprocessedDF

In [8]:
all_data.shape

(37210, 46)

In [9]:
all_data.head()

adult  ...     red_sd 
0  False  ...   88.574055
1  False  ...   85.319415
2  False  ...   96.124722
3  False  ...   72.849543
4  False  ...  104.796367

[5 rows x 46 columns]

In [10]:
all_data = all_data[all_data.original_language == 'en']
print(all_data.shape)

(26824, 46)


In [11]:
pd.to_datetime(all_data.release_date)
all_data['year'] = pd.DatetimeIndex(all_data['release_date']).year
all_data = all_data.loc[all_data.year > 1980]
print(all_data.shape)

(19511, 47)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [12]:
score_by_genre = all_data.groupby(['Genre'])['IMDB Score'].agg(
    ['mean', 'count']).sort_values(by='mean')
score_by_genre[score_by_genre['count'] > 0]

mean  count
Genre                                  
Biography|Horror|Sci-Fi      1.9      1
Sci-Fi|Action|Drama          2.1      1
Horror|Music|Thriller        2.7      1
Animation|Family|Sci-Fi      2.8      1
Adventure|Action|Fantasy     2.8      1
...                          ...    ...
Comedy|Music|Talk-Show       8.4      1
Documentary|History|Sci-Fi   8.4      1
Adventure|Musical            8.6      1
Drama|Musical|Thriller       8.7      1
Music|Musical                8.8      1

[878 rows x 2 columns]

In [13]:
all_data.shape

(19511, 47)

In [14]:
all_data.loc[1]

adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            65000000
genres                   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
homepage                                                               NaN
id                                                                    8844
imdb_id                                                             113497
original_language                                                       en
original_title                                                     Jumanji
overview                 When siblings Judy and Peter discover an encha...
popularity                                                         17.0155
poster_path                               /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
production_companies     [{'name': 'TriStar Pictures', 'id': 559}, {'na...
production_countries     

In [15]:
(all_data.loc[1, 'cast'])

"[{'cast_id': 1, 'character': 'Alan Parrish', 'credit_id': '52fe44bfc3a36847f80a7c73', 'gender': 2, 'id': 2157, 'name': 'Robin Williams', 'order': 0, 'profile_path': '/sojtJyIV3lkUeThD7A2oHNm8183.jpg'}, {'cast_id': 8, 'character': 'Samuel Alan Parrish / Van Pelt', 'credit_id': '52fe44bfc3a36847f80a7c99', 'gender': 2, 'id': 8537, 'name': 'Jonathan Hyde', 'order': 1, 'profile_path': '/7il5D76vx6QVRVlpVvBPEC40MBi.jpg'}, {'cast_id': 2, 'character': 'Judy Sheperd', 'credit_id': '52fe44bfc3a36847f80a7c77', 'gender': 1, 'id': 205, 'name': 'Kirsten Dunst', 'order': 2, 'profile_path': '/wBXvh6PJd0IUVNpvatPC1kzuHtm.jpg'}, {'cast_id': 24, 'character': 'Peter Shepherd', 'credit_id': '52fe44c0c3a36847f80a7ce7', 'gender': 0, 'id': 145151, 'name': 'Bradley Pierce', 'order': 3, 'profile_path': '/j6iW0vVA23GQniAPSYI6mi4hiEW.jpg'}, {'cast_id': 10, 'character': 'Sarah Whittle', 'credit_id': '52fe44bfc3a36847f80a7c9d', 'gender': 1, 'id': 5149, 'name': 'Bonnie Hunt', 'order': 4, 'profile_path': '/7spiVQwmr

In [16]:
from ast import literal_eval

In [17]:
def get_production_companies(l):
  if isinstance(l, list):
    productionCompanies = [pc['name'] for pc in l]
    return '|'.join(productionCompanies)
  return ''

In [18]:
def get_production_countries(l):
  if isinstance(l, list):
    productionCountries = [pc['iso_3166_1'] for pc in l]
    return '|'.join(productionCountries)

In [19]:
def get_keywords(l):
  if isinstance(l, list):
    keyWords = [k['name'] for k in l]
    return '|'.join(keyWords)

In [20]:
title_stop_words = {'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [21]:
def get_original_title(s):
  if isinstance(s, str):
    s = s.lower()
    temp = s.split()
    temp2 = [x for x in temp if x not in title_stop_words]
    print(len(temp) - len(temp2))
    title_words = ['title-' + t for t in temp2]
    return '|'.join(title_words)
  return ''

In [22]:
def get_director(l):
  for d in l:
    if d['job'] == 'Director':
      return d['name']
  return ''

def get_actors(l):
    if isinstance(l, list):
        actors = [d['name'] for d in l]
        if len(actors) >= 3:
            actors = actors[:3]
            return '|'.join(actors)
        return '|'.join(actors)


directors = all_data['crew'].apply(literal_eval).apply(get_director)
top_actors = all_data['cast'].apply(literal_eval).apply(get_actors)

In [23]:
production_companies = all_data['production_companies'].apply(literal_eval).apply(get_production_companies)

In [24]:
production_countries = all_data['production_countries'].apply(literal_eval).apply(get_production_countries)

In [25]:
keywords = all_data['keywords'].apply(literal_eval).apply(get_keywords)

In [26]:
original_title = all_data['original_title'].apply(get_original_title)

Streaming output truncated to the last 5000 lines.
1
0
1
0
0
2
0
0
0
0
0
2
1
0
0
0
0
0
1
2
0
0
3
0
0
1
0
1
1
0
0
0
1
1
0
1
0
2
2
1
3
0
2
0
1
2
0
0
2
0
1
1
0
0
0
0
0
0
0
0
1
0
0
2
1
1
0
1
1
1
0
0
1
4
0
1
0
1
0
0
1
1
0
1
2
0
0
0
0
0
1
0
0
1
0
2
1
0
0
1
1
2
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
1
1
1
0
0
1
2
1
0
1
4
3
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
1
0
1
0
1
0
0
0
2
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
4
1
0
0
0
0
0
3
1
0
0
0
1
0
1
1
0
2
1
1
0
2
0
1
0
1
0
1
0
0
0
0
0
2
1
1
0
2
0
0
1
0
0
0
2
2
3
0
0
0
0
1
3
0
0
0
1
1
0
0
1
0
0
0
2
0
0
3
1
0
1
0
3
0
1
1
0
0
1
0
1
1
2
1
1
0
2
1
2
0
1
0
0
1
0
1
0
1
1
0
1
2
1
1
1
0
1
1
1
1
1
0
0
1
0
1
2
2
0
2
0
0
0
4
4
1
0
0
2
0
2
0
1
1
0
2
0
1
0
0
0
0
0
1
1
1
1
1
0
0
2
2
2
0
1
1
0
0
4
2
0
0
2
1
0
0
0
1
1
0
0
3
1
0
0
1
2
2
1
1
2
0
3
1
0
0
2
1
1
1
0
3
0
1
3
0
0
2
1
2
0
0
5
2
0
1
0
0
0
0
0
2
0
1
1
3
0
1
1
0
0
2
1
2
2
2
2
2
2
2
2
1
1
2
0
2
0
1
3
3
2
5
0
0
2
0
4
2
0
2
6
4
2
0
1
2
0
1
2
0
0
0
0
0
1
0
2
1
0
1
0
0
0
1
0
0
0
2
1
2
1
1
0
1
1
0
0
0
0
0
0
1
0
1
1
0
0
2
0

In [27]:
all_data['director'] = directors
all_data['actors'] = top_actors
all_data['production_companies'] = production_companies
all_data['production_countries'] = production_countries
all_data['keywords'] = keywords
all_data['original_title'] = original_title

In [28]:
all_data.shape

(19511, 49)

In [29]:
all_data.head()

adult  ...                                         actors
0  False  ...                Tom Hanks|Tim Allen|Don Rickles
1  False  ...     Robin Williams|Jonathan Hyde|Kirsten Dunst
2  False  ...         Walter Matthau|Jack Lemmon|Ann-Margret
3  False  ...  Whitney Houston|Angela Bassett|Loretta Devine
4  False  ...         Steve Martin|Diane Keaton|Martin Short

[5 rows x 49 columns]

In [30]:
cols = ['posterID', 'IMDB Score', 'overview', 'Genre', 'director', 'actors', 'production_companies', 'production_countries', 'keywords', 'original_title', 'runtime',
        'num_faces', 'hue', 'hue_sd', 'saturation', 'saturation_sd ', 'brightness', 'brightness_sd', 'blue', 'blue_sd', 'green', 'green_sd', 'red', 'red_sd ']
new_cols = ['posterID', 'IMDBscore', 'overview', 'genre', 'director', 'actors', 'production_companies', 'production_countries', 'keywords', 'original_title', 'runtime',
            'num_faces', 'hue', 'hue_sd', 'saturation', 'saturation_sd', 'brightness', 'brightness_sd', 'blue', 'blue_sd', 'green', 'green_sd', 'red', 'red_sd']

In [31]:
all_data = all_data[cols]
all_data = all_data.dropna()
print(all_data.shape)

(19429, 24)


In [32]:
all_data.columns = new_cols
all_data = all_data.reset_index(drop=True)
print(all_data.shape)

(19429, 24)


In [33]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19429 entries, 0 to 19428
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posterID              19429 non-null  object 
 1   IMDBscore             19429 non-null  float64
 2   overview              19429 non-null  object 
 3   genre                 19429 non-null  object 
 4   director              19429 non-null  object 
 5   actors                19429 non-null  object 
 6   production_companies  19429 non-null  object 
 7   production_countries  19429 non-null  object 
 8   keywords              19429 non-null  object 
 9   original_title        19429 non-null  object 
 10  runtime               19429 non-null  float64
 11  num_faces             19429 non-null  float64
 12  hue                   19429 non-null  float64
 13  hue_sd                19429 non-null  float64
 14  saturation            19429 non-null  float64
 15  saturation_sd      

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
train_dataset, test_dataset = train_test_split(
    all_data, test_size=0.3, random_state=0)
valid_dataset, test_dataset = train_test_split(
    test_dataset, test_size=0.5, random_state=0)

train_data = train_dataset.reset_index(drop=True)
valid_data = valid_dataset.reset_index(drop=True)
test_data = test_dataset.reset_index(drop=True)

print(train_data.shape)
print(valid_data.shape)
print(test_data.shape)

train_data.to_csv('train.csv', index=False)
valid_data.to_csv('valid.csv', index=False)
test_data.to_csv('test.csv', index=False)

print('')
print(np.cov(train_data['IMDBscore']))
print(np.cov(valid_data['IMDBscore']))
print(np.cov(test_data['IMDBscore']))

(13600, 24)
(2914, 24)
(2915, 24)

1.4948912934233927
1.4929201393134843
1.4876570362984156


In [36]:
def get_words(message, tokenizer = None):
    if tokenizer:
        doc = tokenizer(message)
        return [i.text for i in doc]
    else:
        return message.lower().split('|')

def create_dictionary(messages, min_count = 5, tokenizer = None):
    words_count = {}
    for i in tqdm(range(len(messages))):
        s = messages[i]
        words = get_words(s, tokenizer)
        words_unique = list(dict.fromkeys(words))
        for w in words_unique:
            if w not in words_count:
                words_count[w] = 1
            else:
                words_count[w] += 1

    for word in list(words_count.keys()):
        if (words_count[word] < min_count) or word=='':
            del words_count[word]

    index = 1
    for word in list(words_count.keys()):
        words_count[word] = index
        index = index + 1

    return words_count


def transform_text(messages, word_dictionary, tokenizer = None):
    words_arr = np.zeros((len(messages), len(word_dictionary)))
    for i in range(words_arr.shape[0]):
        message_words = get_words(messages[i], tokenizer)
        message_indices = map(word_dictionary.get, message_words)
        for j in message_indices:
            if j is not None:
                words_arr[i, j-1] += 1
    return words_arr

In [37]:
production_companies_dictionary = create_dictionary(train_data['production_companies'].astype(str).values, min_count=100)
print('Size of dictionary: ', len(production_companies_dictionary))
train_production_companies_matrix = transform_text(train_data['production_companies'].astype(str).values, production_companies_dictionary)
valid_production_companies_matrix = transform_text(valid_data['production_companies'].astype(str).values, production_companies_dictionary)
test_production_companies_matrix = transform_text(test_data['production_companies'].astype(str).values, production_companies_dictionary)
# print(director_dictionary)
print(train_production_companies_matrix.shape)
print(valid_production_companies_matrix.shape)
print(test_production_companies_matrix.shape)

100%|██████████| 13600/13600 [00:00<00:00, 268555.52it/s]

Size of dictionary:  12
(13600, 12)
(2914, 12)
(2915, 12)


In [38]:
print(production_companies_dictionary)

{'warner bros.': 1, 'twentieth century fox film corporation': 2, 'touchstone pictures': 3, 'universal pictures': 4, 'walt disney pictures': 5, 'paramount pictures': 6, 'tristar pictures': 7, 'metro-goldwyn-mayer (mgm)': 8, 'columbia pictures corporation': 9, 'miramax films': 10, 'columbia pictures': 11, 'new line cinema': 12}


In [39]:
print(train_production_companies_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
cnt = 0
for i in tqdm(range(train_production_companies_matrix.shape[0])):
    for j in range(train_production_companies_matrix.shape[1]):
        cnt += train_production_companies_matrix[i,j]
cnt

100%|██████████| 13600/13600 [00:00<00:00, 107461.77it/s]


2473.0

In [41]:
production_countries_dictionary = create_dictionary(train_data['production_countries'].astype(str).values, min_count=20)
print('Size of dictionary: ', len(production_countries_dictionary))
train_production_countries_matrix = transform_text(train_data['production_countries'].astype(str).values, production_countries_dictionary)
valid_production_countries_matrix = transform_text(valid_data['production_countries'].astype(str).values, production_countries_dictionary)
test_production_countries_matrix = transform_text(test_data['production_countries'].astype(str).values, production_countries_dictionary)
# print(director_dictionary)
print(train_production_countries_matrix.shape)
print(valid_production_countries_matrix.shape)
print(test_production_countries_matrix.shape)

100%|██████████| 13600/13600 [00:00<00:00, 475437.65it/s]

Size of dictionary:  37
(13600, 37)
(2914, 37)
(2915, 37)


In [42]:
print(production_countries_dictionary)

{'us': 1, 'gb': 2, 'fr': 3, 'it': 4, 'be': 5, 'es': 6, 'nl': 7, 'ru': 8, 'se': 9, 'de': 10, 'at': 11, 'ca': 12, 'cn': 13, 'hk': 14, 'ch': 15, 'au': 16, 'ie': 17, 'kr': 18, 'ph': 19, 'fi': 20, 'no': 21, 'mx': 22, 'hu': 23, 'in': 24, 'dk': 25, 'ar': 26, 'nz': 27, 'ro': 28, 'jp': 29, 'lu': 30, 'br': 31, 'za': 32, 'il': 33, 'gr': 34, 'pl': 35, 'cz': 36, 'pt': 37}


In [43]:
print(train_production_countries_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [44]:
tnc = 0
for i in tqdm(range(train_production_countries_matrix.shape[0])):
    for j in range(train_production_countries_matrix.shape[1]):
        tnc += train_production_countries_matrix[i,j]
tnc

100%|██████████| 13600/13600 [00:00<00:00, 42443.40it/s]


14349.0

In [45]:
keywords_dictionary = create_dictionary(train_data['keywords'].astype(str).values, min_count=30)
print('Size of dictionary: ', len(keywords_dictionary))
train_keywords_matrix = transform_text(train_data['keywords'].astype(str).values, keywords_dictionary)
valid_keywords_matrix = transform_text(valid_data['keywords'].astype(str).values, keywords_dictionary)
test_keywords_matrix = transform_text(test_data['keywords'].astype(str).values, keywords_dictionary)
# print(director_dictionary)
print(train_keywords_matrix.shape)
print(valid_keywords_matrix.shape)
print(test_keywords_matrix.shape)

100%|██████████| 13600/13600 [00:00<00:00, 265399.29it/s]


Size of dictionary:  254
(13600, 254)
(2914, 254)
(2915, 254)


In [46]:
print(keywords_dictionary)

{'independent film': 1, 'woman director': 2, 'sex': 3, 'eroticism': 4, 'marriage': 5, 'war': 6, 'crime': 7, 'london england': 8, 'scientist': 9, 'nightmare': 10, 'usa president': 11, 'hitman': 12, 'serial killer': 13, 'fbi agent': 14, 'england': 15, 'based on novel': 16, 'africa': 17, 'wilderness': 18, 'based on true story': 19, 'superhero': 20, 'super powers': 21, 'biography': 22, 'politics': 23, 'love triangle': 24, 'dark comedy': 25, 'jealousy': 26, 'high school': 27, 'orphan': 28, 'teenager': 29, 'friendship': 30, 'coming of age': 31, 'best friend': 32, 'murder': 33, 'suspense': 34, 'lawyer': 35, 'killer': 36, 'musician': 37, 'father daughter relationship': 38, 'martial arts': 39, 'falling in love': 40, 'father son relationship': 41, 'baseball': 42, 'sport': 43, 'musical': 44, 'journalist': 45, '1970s': 46, 'extramarital affair': 47, 'dance': 48, 'baby': 49, 'drug dealer': 50, 'prison': 51, 'police': 52, 'racism': 53, 'violence': 54, 'magic': 55, 'love': 56, 'comedy': 57, 'animatio

In [47]:
qwqwqw = 0
for i in tqdm(range(train_keywords_matrix.shape[0])):
    for j in range(train_keywords_matrix.shape[1]):
        qwqwqw += train_keywords_matrix[i,j]
qwqwqw

100%|██████████| 13600/13600 [00:02<00:00, 6052.11it/s]


18930.0

In [48]:
original_title_dictionary = create_dictionary(train_data['original_title'].astype(str).values, min_count=5)
print('Size of dictionary: ', len(original_title_dictionary))
train_original_title_matrix = transform_text(train_data['original_title'].astype(str).values, original_title_dictionary)
valid_original_title_matrix = transform_text(valid_data['original_title'].astype(str).values, original_title_dictionary)
test_original_title_matrix = transform_text(test_data['original_title'].astype(str).values, original_title_dictionary)
# print(director_dictionary)
print(train_original_title_matrix.shape)
print(valid_original_title_matrix.shape)
print(test_original_title_matrix.shape)

100%|██████████| 13600/13600 [00:00<00:00, 384718.08it/s]


Size of dictionary:  1132
(13600, 1132)
(2914, 1132)
(2915, 1132)


In [49]:
print(original_title_dictionary)

{'title-happiness': 1, 'title-sex': 2, 'title-journey': 3, 'title-planet': 4, 'title-x': 5, 'title-future': 6, 'title-milk': 7, 'title-big': 8, 'title-adventure': 9, 'title-new': 10, 'title-york': 11, 'title-desert': 12, 'title-special': 13, 'title-cold': 14, 'title-cinderella': 15, 'title-story': 16, 'title-revenge': 17, 'title-edge': 18, 'title-murder': 19, 'title-trouble': 20, 'title-truth': 21, 'title-bruce': 22, 'title-le': 23, 'title-de': 24, 'title-la': 25, 'title-sweet': 26, 'title-soul': 27, 'title-game': 28, 'title-killer': 29, 'title-happy': 30, 'title-end': 31, 'title-world': 32, 'title-hearts': 33, 'title-apocalypse': 34, 'title-one': 35, 'title-wish': 36, 'title-dead': 37, 'title-girl': 38, 'title-secret': 39, 'title-lost': 40, 'title-legend': 41, 'title-darkness': 42, 'title-forever': 43, 'title-belle': 44, 'title-lies': 45, 'title-life': 46, 'title-far': 47, 'title-two': 48, 'title-mrs.': 49, 'title-miracle': 50, 'title-&': 51, 'title-made': 52, 'title-sing': 53, 'title

In [50]:
ytytyt = 0
for i in tqdm(range(train_original_title_matrix.shape[0])):
    for j in range(train_original_title_matrix.shape[1]):
        ytytyt += train_original_title_matrix[i,j]
ytytyt

100%|██████████| 13600/13600 [00:07<00:00, 1817.20it/s]


14883.0

In [51]:
# min count is denoting the minimum number of times a word has to appear in the corpus to be included in the dictionary
genre_dictionary = create_dictionary(
    train_data['genre'].astype(str).values, min_count=5)

100%|██████████| 13600/13600 [00:00<00:00, 406998.98it/s]


In [52]:
print(genre_dictionary)

{'drama': 1, 'comedy': 2, 'romance': 3, 'biography': 4, 'action': 5, 'thriller': 6, 'fantasy': 7, 'documentary': 8, 'horror': 9, 'crime': 10, 'history': 11, 'family': 12, 'short': 13, 'music': 14, 'sport': 15, 'animation': 16, 'sci-fi': 17, 'adventure': 18, 'mystery': 19, 'musical': 20, 'war': 21, 'western': 22, 'news': 23}


In [53]:
train_genre_matrix = transform_text(
    train_data['genre'].astype(str).values, genre_dictionary)
valid_genre_matrix = transform_text(
    valid_data['genre'].astype(str).values, genre_dictionary)
test_genre_matrix = transform_text(
    test_data['genre'].astype(str).values, genre_dictionary)
# print(genre_dictionary)
print(train_genre_matrix.shape)
print(valid_genre_matrix.shape)
print(test_genre_matrix.shape)

(13600, 23)
(2914, 23)
(2915, 23)


In [54]:
train_data.head()

posterID  IMDBscore  ...         red     red_sd
0  32402.jpg        4.9  ...   89.145326  90.019602
1  13923.jpg        6.1  ...  194.170035  65.356209
2  11038.jpg        6.1  ...   78.617798  65.191101
3  17344.jpg        6.4  ...  199.685224  67.837758
4    501.jpg        7.2  ...  140.103072  98.594190

[5 rows x 24 columns]

In [55]:
director_dictionary = create_dictionary(
    train_data['director'].astype(str).values, min_count=5)
print('Size of dictionary: ', len(director_dictionary))
train_director_matrix = transform_text(
    train_data['director'].astype(str).values, director_dictionary)
valid_director_matrix = transform_text(
    valid_data['director'].astype(str).values, director_dictionary)
test_director_matrix = transform_text(
    test_data['director'].astype(str).values, director_dictionary)
# print(director_dictionary)
print(train_director_matrix.shape)
print(valid_director_matrix.shape)
print(test_director_matrix.shape)


100%|██████████| 13600/13600 [00:00<00:00, 465368.42it/s]

Size of dictionary:  491
(13600, 491)
(2914, 491)
(2915, 491)


In [56]:
print(director_dictionary)

{'ken loach': 1, 'sally potter': 2, 'bernard rose': 3, 'bruce beresford': 4, 'mike newell': 5, 'richard loncraine': 6, 'mark rosman': 7, 'patrice leconte': 8, 'atom egoyan': 9, 'dick lowry': 10, 'jay duplass': 11, 'steve james': 12, 'susan seidelman': 13, 'michael apted': 14, 'robert zemeckis': 15, 'nick broomfield': 16, 'todd phillips': 17, 'george a. romero': 18, 'rob reiner': 19, 'mike leigh': 20, 'robert altman': 21, 'joe johnston': 22, 'julien temple': 23, 'albert pyun': 24, 'carlos saura': 25, 'brian trenchard-smith': 26, 'charles band': 27, 'stewart raffill': 28, 'werner herzog': 29, 'garry marshall': 30, 'tim story': 31, 'uwe boll': 32, 'harold ramis': 33, 'mikael hã¥fstrã¶m': 34, 'miguel arteta': 35, 'francis ford coppola': 36, 'michael mann': 37, 'shawn levy': 38, 'james benning': 39, 'ben stiller': 40, 'roger donaldson': 41, 'ridley scott': 42, 'neil jordan': 43, 'sean mcnamara': 44, 'christopher cain': 45, 'joe carnahan': 46, 'mike figgis': 47, 'brian robbins': 48, 'john st

In [57]:
actors_dictionary = create_dictionary(
    train_data['actors'].astype(str).values, min_count=5)
print('Size of dictionary: ', len(actors_dictionary))
train_actors_matrix = transform_text(
    train_data['actors'].astype(str).values, actors_dictionary)
valid_actors_matrix = transform_text(
    valid_data['actors'].astype(str).values, actors_dictionary)
test_actors_matrix = transform_text(
    test_data['actors'].astype(str).values, actors_dictionary)
# print(actors_dictionary)
print(train_actors_matrix.shape)
print(valid_actors_matrix.shape)
print(test_actors_matrix.shape)


100%|██████████| 13600/13600 [00:00<00:00, 346010.11it/s]


Size of dictionary:  1602
(13600, 1602)
(2914, 1602)
(2915, 1602)


In [58]:
print(actors_dictionary)

{'mark duplass': 1, 'joshua leonard': 2, 'tilda swinton': 3, 'billy zane': 4, 'glenne headly': 5, 'james cosmo': 6, 'jake johnson': 7, 'morgan freeman': 8, 'john cusack': 9, 'alice krige': 10, 'alan rickman': 11, 'hugh grant': 12, 'sally hawkins': 13, 'kris lemche': 14, 'brooke nevin': 15, 'michael sheen': 16, 'dennis quaid': 17, 'hope davis': 18, 'john lithgow': 19, 'teri garr': 20, 'randy quaid': 21, 'hilary duff': 22, 'jennifer coolidge': 23, 'chad michael murray': 24, 'robert carradine': 25, 'anthony edwards': 26, 'hailee steinfeld': 27, 'cuba gooding jr.': 28, 'tom berenger': 29, 'edward norton': 30, 'naomi watts': 31, 'lea thompson': 32, 'danielle harris': 33, 'jackie chan': 34, 'ian holm': 35, 'sarah polley': 36, 'billy crudup': 37, 'anton yelchin': 38, 'delroy lindo': 39, 'blair underwood': 40, 'harry connick jr.': 41, 'mickey rooney': 42, 'gina gershon': 43, 'liev schreiber': 44, 'cary elwes': 45, 'christopher lloyd': 46, 'lacey chabert': 47, 'william katt': 48, 'sean young': 

In [59]:
import spacy
import re

In [60]:
#def func(messages, word_dictionary, tokenizer = None):
#  m_w = get_words_new(messages[0],tokenizer)
#  m_i = map(word_dictionary.get,m_w)
#  print(m_w)
#  print(list(m_i))

In [61]:
def create_dictionary_overview(messages, min_count, tokenizer):
    stop_words = []
    with open(path2,'r') as f:
      for x in f:
        stop_words.append(x[:-1])

    words_count = {}
    for i in tqdm(range(len(messages))):
        s = messages[i]
        words = get_words(s, tokenizer)
        words_unique = list(dict.fromkeys(words))
        for w in words_unique:
          if len(w)<=1 or w.lower()in stop_words:
            continue
          if w.lower() not in words_count:
            words_count[w.lower()] = 1
          else:
            words_count[w.lower()] += 1

    for word in list(words_count.keys()):
        if (words_count[word] < min_count) or word=='':
            del words_count[word]

    index = 1
    for word in list(words_count.keys()):
        words_count[word] = index
        index = index + 1

    return words_count

In [62]:
def get_words_new(message, tokenizer = None):
  if tokenizer:
    doc = tokenizer(message)
    return [i.text for i in doc]
  else:
    return message.lower().split(' ')

In [63]:
def custom_transform(messages, word_dictionary, tokenizer = None):
    words_arr = np.zeros((len(messages), len(word_dictionary)))
    for i in range(words_arr.shape[0]):
        message_words = get_words_new(messages[i], tokenizer)
        message_indices = map(word_dictionary.get, message_words)
        for j in message_indices:
            if j is not None:
                words_arr[i, j-1] += 1
    return words_arr

In [64]:
tokenizer = spacy.load("en_core_web_sm", disable=["tagger", "parser", "ner", "lemmatizer"])
overview_dictionary = create_dictionary_overview(
    train_data['overview'], 30, tokenizer)
print('Size of dictionary: ', len(overview_dictionary))

train_overview_matrix = custom_transform(
    train_data['overview'].astype(str).values, overview_dictionary)

valid_overview_matrix = custom_transform(
    valid_data['overview'].astype(str).values, overview_dictionary)

test_overview_matrix = custom_transform(
    test_data['overview'].astype(str).values, overview_dictionary)

# print(overview_dictionary)
print(train_overview_matrix.shape)
print(valid_overview_matrix.shape)
print(test_overview_matrix.shape)


100%|██████████| 13600/13600 [00:19<00:00, 685.96it/s]


Size of dictionary:  2153
(13600, 2153)
(2914, 2153)
(2915, 2153)


In [65]:
train_overview_matrix

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [66]:
train_overview_matrix.sum(axis=0)

array([167., 229., 412., ...,  31.,  38.,  21.])

In [67]:
train_overview_matrix.sum(axis=1)

array([ 7., 12., 12., ...,  1.,  3., 13.])

In [68]:
print(overview_dictionary)

{'child': 1, 'parents': 2, 'living': 3, 'victor': 4, 'sex': 5, 'drugs': 6, 'smart': 7, 'survive': 8, 'life': 9, 'complete': 10, 'house': 11, 'job': 12, 'wife': 13, 'friend': 14, 'college': 15, 'door': 16, 'party': 17, 'plan': 18, 'friends': 19, 'create': 20, 'art': 21, 'film': 22, 'straight': 23, 'lives': 24, 'moments': 25, 'wedding': 26, 'obsession': 27, 'romantic': 28, 'sexual': 29, 'history': 30, 'including': 31, 'commitment': 32, 'relationships': 33, 'led': 34, 'disastrous': 35, 'girlfriends': 36, "'s": 37, 'unique': 38, 'brand': 39, 'comedy': 40, 'private': 41, 'security': 42, 'iraq': 43, 'official': 44, 'death': 45, 'decides': 46, 'investigate': 47, 'queen': 48, 'elizabeth': 49, 'change': 50, 'affair': 51, 'russian': 52, 'princess': 53, 'arts': 54, 'war': 55, 'morning': 56, 'shocked': 57, 'wake': 58, 'woman': 59, 'returns': 60, 'struggling': 61, 'female': 62, 'property': 63, 'centuries': 64, 'roll': 65, 'filmmaker': 66, 'widow': 67, 'late': 68, 'meeting': 69, 'women': 70, 'eric':

In [69]:
train_overview_matrix.shape

(13600, 2153)

In [70]:
count = 0
for i in tqdm(range(train_overview_matrix.shape[0])):
    for j in range(train_overview_matrix.shape[1]):
        count += train_overview_matrix[i,j]
count

100%|██████████| 13600/13600 [00:13<00:00, 1042.98it/s]


160740.0

In [71]:
for i in overview_dictionary:
    print(i, overview_dictionary[i])

child 1
parents 2
living 3
victor 4
sex 5
drugs 6
smart 7
survive 8
life 9
complete 10
house 11
job 12
wife 13
friend 14
college 15
door 16
party 17
plan 18
friends 19
create 20
art 21
film 22
straight 23
lives 24
moments 25
wedding 26
obsession 27
romantic 28
sexual 29
history 30
including 31
commitment 32
relationships 33
led 34
disastrous 35
girlfriends 36
's 37
unique 38
brand 39
comedy 40
private 41
security 42
iraq 43
official 44
death 45
decides 46
investigate 47
queen 48
elizabeth 49
change 50
affair 51
russian 52
princess 53
arts 54
war 55
morning 56
shocked 57
wake 58
woman 59
returns 60
struggling 61
female 62
property 63
centuries 64
roll 65
filmmaker 66
widow 67
late 68
meeting 69
women 70
eric 71
scientists 72
day 73
amateur 74
filmmakers 75
night 76
inspired 77
movies 78
journey 79
planet 80
filming 81
ambitious 82
light 83
anna 84
lost 85
discovers 86
visit 87
drawn 88
boy 89
fantasy 90
deeper 91
dream 92
nightmare 93
fatal 94
accident 95
left 96
term 97
memory 98
bound

# Encoding 

In [72]:
train_data = pd.read_csv('train.csv')
valid_data = pd.read_csv('valid.csv')
test_data = pd.read_csv('test.csv')
train_data = train_data.drop(columns = ['overview','genre','director','actors','production_companies','production_countries','keywords','original_title'])
valid_data = valid_data.drop(columns = ['overview','genre','director','actors','production_companies','production_countries','keywords','original_title'])
test_data = test_data.drop(columns = ['overview','genre','director','actors','production_companies','production_countries','keywords','original_title'])
train_data = pd.concat([train_data,
                        pd.DataFrame(train_genre_matrix, columns = genre_dictionary.keys()),
                        pd.DataFrame(train_director_matrix, columns = director_dictionary.keys()), 
                        pd.DataFrame(train_actors_matrix, columns = actors_dictionary.keys()),
                        pd.DataFrame(train_overview_matrix, columns = overview_dictionary.keys()),
                        pd.DataFrame(train_production_companies_matrix, columns = production_companies_dictionary.keys()),
                        pd.DataFrame(train_production_countries_matrix, columns = production_countries_dictionary.keys()),
                        pd.DataFrame(train_keywords_matrix, columns=keywords_dictionary.keys())],
                        axis=1)

valid_data = pd.concat([valid_data,
                        pd.DataFrame(valid_genre_matrix, columns = genre_dictionary.keys()),
                        pd.DataFrame(valid_director_matrix, columns = director_dictionary.keys()), 
                        pd.DataFrame(valid_actors_matrix, columns = actors_dictionary.keys() ),
                        pd.DataFrame(valid_overview_matrix, columns = overview_dictionary.keys()),
                        pd.DataFrame(valid_production_companies_matrix, columns = production_companies_dictionary.keys()),
                        pd.DataFrame(valid_production_countries_matrix, columns = production_countries_dictionary.keys()),
                        pd.DataFrame(train_keywords_matrix, columns=keywords_dictionary.keys())],
                        axis=1)

test_data = pd.concat([test_data,
                       pd.DataFrame(test_genre_matrix, columns = genre_dictionary.keys()),
                       pd.DataFrame(test_director_matrix, columns = director_dictionary.keys()), 
                       pd.DataFrame(test_actors_matrix, columns = actors_dictionary.keys()),
                       pd.DataFrame(test_overview_matrix, columns = overview_dictionary.keys()),
                       pd.DataFrame(test_production_companies_matrix, columns = production_companies_dictionary.keys()),
                       pd.DataFrame(test_production_countries_matrix, columns = production_countries_dictionary.keys()),
                       pd.DataFrame(test_keywords_matrix, columns=keywords_dictionary.keys())],
                       axis=1)

In [73]:
train_data.to_csv('train1.csv', index=False)
valid_data.to_csv('valid1.csv', index=False)
test_data.to_csv('test1.csv', index=False)


In [74]:
train_data = pd.read_csv('train1.csv', low_memory=False)
valid_data = pd.read_csv('valid1.csv', low_memory=False)
test_data = pd.read_csv('test1.csv', low_memory=False)


In [75]:
train_data.shape

(13600, 4588)

In [76]:
train_data

posterID  IMDBscore  runtime  ...  concert.1  dysfunctional family  hero.1
0      32402.jpg        4.9     88.0  ...        0.0                   0.0     0.0
1      13923.jpg        6.1     94.0  ...        0.0                   0.0     0.0
2      11038.jpg        6.1     98.0  ...        0.0                   0.0     0.0
3      17344.jpg        6.4    109.0  ...        0.0                   0.0     0.0
4        501.jpg        7.2     93.0  ...        0.0                   0.0     0.0
...          ...        ...      ...  ...        ...                   ...     ...
13595  17585.jpg        6.5    103.0  ...        0.0                   1.0     0.0
13596  24976.jpg        7.3     80.0  ...        0.0                   0.0     0.0
13597  18879.jpg        6.9     48.0  ...        0.0                   0.0     0.0
13598  20618.jpg        2.0     89.0  ...        0.0                   0.0     0.0
13599   3962.jpg        5.9    109.0  ...        0.0                   0.0     0.0

[13600 rows x 4588 columns]

## normailizing the data

In [77]:
for col in ['runtime', 'num_faces', 'hue', 'hue_sd', 'saturation', 'saturation_sd', 'brightness', 'brightness_sd',
            'blue', 'blue_sd', 'green', 'green_sd', 'red', 'red_sd']:
    mean_feature = np.mean(train_data[col])
    sd_feature = np.std(train_data[col])
    if sd_feature != 0:
        train_data[col] = (train_data[col] - mean_feature) / sd_feature
        valid_data[col] = (valid_data[col] - mean_feature) / sd_feature
        test_data[col] = (test_data[col] - mean_feature) / sd_feature
    else:
        train_data[col] = (train_data[col] - mean_feature)
        valid_data[col] = (valid_data[col] - mean_feature)
        test_data[col] = (test_data[col] - mean_feature)


In [78]:
print(train_data.shape)
print(valid_data.shape)
print(test_data.shape)
train_X = train_data.drop(columns=['posterID', 'IMDBscore'])
valid_X = valid_data.drop(columns=['posterID', 'IMDBscore'])
test_X = test_data.drop(columns=['posterID', 'IMDBscore'])

(13600, 4588)
(13600, 4588)
(2915, 4588)


# Linear Regression

In [79]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [80]:
print(np.cov(train_data['IMDBscore']))
print(np.cov(valid_data['IMDBscore']))
print(np.cov(test_data['IMDBscore']))


1.4948912934233927
nan
1.4876570362984156


In [81]:
reg = LinearRegression().fit(train_X, train_data['IMDBscore'])

print('Train R^2: ', reg.score(train_X, train_data['IMDBscore']))
print('Train MSE: ', mean_squared_error(
    reg.predict(train_X), train_data['IMDBscore']))

print('Valid R^2: ', reg.score(valid_X, valid_data['IMDBscore']))
print('Valid MSE: ', mean_squared_error(
    reg.predict(valid_X), valid_data['IMDBscore']))

print('Test R^2: ', reg.score(test_X, test_data['IMDBscore']))
print('Test MSE: ', mean_squared_error(
    reg.predict(test_X), test_data['IMDBscore']))

Train R^2:  0.6598681869407426
Train MSE:  0.5084226991875703


ValueError: ignored

In [ ]:
reg = Ridge(alpha=10, random_state=0).fit(train_X, train_data['IMDBscore'])

print('Train R^2: ', reg.score(train_X, train_data['IMDBscore']))
print('Train MSE: ', mean_squared_error(
    reg.predict(train_X), train_data['IMDBscore']))

print('Valid R^2: ', reg.score(valid_X, valid_data['IMDBscore']))
print('Valid MSE: ', mean_squared_error(
    reg.predict(valid_X), valid_data['IMDBscore']))

print('Test R^2: ', reg.score(test_X, test_data['IMDBscore']))
print('Test MSE: ', mean_squared_error(
    reg.predict(test_X), test_data['IMDBscore']))


In [ ]:
reg = Lasso(alpha=0.0001, random_state=0).fit(train_X, train_data['IMDBscore'])

print('Train R^2: ', reg.score(train_X, train_data['IMDBscore']))
print('Train MSE: ', mean_squared_error(
    reg.predict(train_X), train_data['IMDBscore']))

print('Valid R^2: ', reg.score(valid_X, valid_data['IMDBscore']))
print('Valid MSE: ', mean_squared_error(
    reg.predict(valid_X), valid_data['IMDBscore']))

print('Test R^2: ', reg.score(test_X, test_data['IMDBscore']))
print('Test MSE: ', mean_squared_error(
    reg.predict(test_X), test_data['IMDBscore']))

In [ ]:
from sklearn.model_selection import learning_curve